### ISSUE TITLE
A question about the result of Multi-label Classification task on Cora dataset

### ISSUE THREAD

**Issue by BenchengY** [thunlp/NEU#1]
I wander that why the auc is so high on cora for Classification task in your paper. 
Do you use the text information of cora? As i run node2vec on cora(just use citation links information) for  Classification the auc is about 30%.
thanks!

**Comment by yangchengbupt** [comment]
No, I just use the link information. The AUC value measures the probability that the score of a missing edge is larger than that of a nonexistent edge. Thus AUC is certainly larger than 50%. I think you should double check your evaluation code.

**Comment by BenchengY** [comment]
I know the auc is certainly larger than 50% for link prediction task.
but what i  want know is for node classification task on cora . 
thanks.
